In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score
from sklearn.preprocessing import LabelEncoder

In [2]:
x=np.array([
    [160,70,90], #Cricket 
    [450,100,90],#football 
    [0,50,30], #Neither
    [155,75,120],#cricket 
    [420,90,95],#football 
    [50,30,60],#neither 
    [165,80,110],#cricket
    [480,105,100],#football
    [20,40,45]#neither
])

In [3]:
x

array([[160,  70,  90],
       [450, 100,  90],
       [  0,  50,  30],
       [155,  75, 120],
       [420,  90,  95],
       [ 50,  30,  60],
       [165,  80, 110],
       [480, 105, 100],
       [ 20,  40,  45]])

In [4]:
#labels:cricket,football,neither
y=np.array(["cricket","football","neither","cricket","football","neither","cricket","football","neither"])


In [5]:
y

array(['cricket', 'football', 'neither', 'cricket', 'football', 'neither',
       'cricket', 'football', 'neither'], dtype='<U8')

In [7]:
#Encode labels
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

In [12]:
y_encoded #dtype?

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [10]:
##split feature and labels
x_train,x_test,y_train,y_test = train_test_split(x,y_encoded,test_size=0.3,random_state=42,stratify=y_encoded)

In [16]:
x_train

array([[480, 105, 100],
       [160,  70,  90],
       [155,  75, 120],
       [420,  90,  95],
       [ 50,  30,  60],
       [  0,  50,  30]])

In [20]:
#Train KNN
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train);

In [21]:
x_test

array([[450, 100,  90],
       [165,  80, 110],
       [ 20,  40,  45]])

In [22]:
#predict
y_pred=knn.predict(x_test)

In [23]:
y_pred

array([1, 0, 2])

In [28]:
#results
cm=confusion_matrix(y_test,y_pred)
print("Confusion matrix: \n",cm)

Confusion matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
fig,ax=plt.subplots(figsize=(12,15))
sns.heatmap(confusion_matrix(y_test,y_pred),annot=True,fmt="d",cmap="Blues",ax=ax)
ax.set_title("Confusion matrix")
ax.set_xlabel("predicted")
ax.set_ylabel("Actual")
plt.show()

In [31]:
print("\n Classification Report:\n",classification_report(y_test,y_pred,target_names=encoder.classes_))


 Classification Report:
               precision    recall  f1-score   support

     cricket       1.00      1.00      1.00         1
    football       1.00      1.00      1.00         1
     neither       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

